default['cfn_metadata']['stack_name']    = ""
default['cfn_metadata']['region']        = ""
default['cfn_metadata']['resource_name'] = ""
default['cfn_metadata']['access_key']    = ""
default['cfn_metadata']['secret_key']    = ""
default['cfn_metadata']['cfn_path']      = "/opt/aws/bin/cfn-get-metadata"
